# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Mon Mar  8 18:28:21 2021
# ------------------------------------------------

package:
  name: defusedxml
  version: 0.7.1
source:
  sha256: 1bb3032db185915b62d7c6209c5a8792be6a32ab2fedacc84e01b52c51aa3e69
  url: https://pypi.io/packages/source/d/defusedxml/defusedxml-0.7.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /tmp/build/80754af9/defusedxml_1615228127516/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - ca-certificates 2021.1.19 h06a4308_0
    - certifi 2020.12.5 py36h06a4308_0
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libedit 3.1.20191231 h14c3975_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1j h27cfd23_0
    - pip 21.0.1 py36h06a4308_0
    - python 3.6.13 hdb3f193_0
    - readline 8.1 h27cfd23_0
    - setuptools 52.0.0 py36h06a4308_0
    - sqlite 3.33.0 h62c20be_0
    - tk 8.6.10 hbc83047_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - python
test:
  imports:
    - defusedxml
about:
  dev_url: https://bitbucket.org/tiran/defusedxml
  doc_url: https://bitbucket.org/tiran/defusedxml
  home: https://bitbucket.org/tiran/defusedxml
  license: PSF 2.0
  license_family: PSF
  license_file: LICENSE
  summary: XML bomb protection for Python stdlib modules
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - pmlandwehr
